version: 2.1

jobs:
  create_and_deploy_frontend:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy frontend
          command: |
            aws cloudformation deploy \
            --template-file bucket.yml \
            --stack-name ${CIRCLE_WORKFLOW_ID:0:7} \
            --parameter-overrides PipelineID=${CIRCLE_WORKFLOW_ID:0:7} \
            --region=us-west-2
      - run: 
          name: Move files there
          command: |
            aws s3 sync . s3://${CIRCLE_WORKFLOW_ID:0:7} --delete
  promote_to_prod:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Promote to prod
          command: |
            aws cloudformation deploy \
            --template-file cloudfront.yml
            --stack-name cloudfront
            --parameter-overrides PipelineID=${CIRCLE_WORKFLOW_ID:0:7}
     
workflows:
  version: 2.1
  promote_to_prod:
    jobs:
      - create_and_deploy_frontend
      - promote_to_prod:
          requires:
            - create_and_deploy_frontend
