version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  test_on_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: exit 1

      - run: 
          name: Warn when something is wrong
          command: echo 'Oopps'
          when: on_fail
  print_workflow_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
workflows:
  version: 2.1
  print_hello_and_world:
    jobs:
      - test_on_fail
      - print_workflow_id