version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy cloud env
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Spin up the infra
          command: aws cloudformation deploy --template-file template.yml --stack-name prod-${CIRCLE_WORKFLOW_ID} --region=us-west-2
      - run: return 1
      - destroy_environment
        when: on_fail

workflows:
  version: 2.1
  print_hello_and_world:
    jobs:
      - create_infra