version: 2.1

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: check webpage
          command: |
            if curl -s --head http://google.com
            then
              echo "It works"
            else
              echo "it doesn't work"

workflows:
  version: 2.1
  smoke_test:
    jobs:
      - smoke_test