version: 2
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "world"
  print_my_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "My name is"
          command: |
            echo $MY_OWN
workflows:
  version: 2
  print_hello_and_world:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_my_name