version: 2.1

jobs:
  create_infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout

      - run: 
          name: Spin up the infra
          command: aws cloudformation deploy --template-file template.yml --region=us-west-2 --stack-name circleci
          when: on_fail
workflows:
  version: 2.1
  print_hello_and_world:
    jobs:
      - create_infra