version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "world"
  print_my_name:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "My name is"
          command: |
            echo $MY_OWN
  save_hello_world_output:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: .
          paths:
            - .
  print_hello_world_output:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: cat output.txt
workflows:
  version: 2.1
  print_hello_and_world:
    jobs:
      - save_hello_world_output
      - print_hello_world_output:
          requires:
            - save_hello_world_output